{"name": "Ошибка авторизации с неверным email или паролем", "status": "passed", "steps": [{"name": "Авторизация пользователя", "status": "passed", "parameters": [{"name": "user_data", "value": "{'email': 'lexef3@gahm.kn', 'password': 0, 'name': 'Wgmkvwvoe'}"}, {"name": "token", "value": "'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmJlMGRlOWVkMjgwMDAxYjUzZDdkYiIsImlhdCI6MTczNTEyMzE2NiwiZXhwIjoxNzM1MTI0MzY2fQ.lHRasG5m6mEQw9F-rokVRpa6Sg2BfKzntsNRB-DzuPQ'"}], "start": 1735123166365, "stop": 1735123166521}], "parameters": [{"name": "field", "value": "'password'"}], "start": 1735123166365, "stop": 1735123166522, "uuid": "82135a26-6c1e-4ba9-bde7-62ed23c4d6f6", "historyId": "11b080a730804009ee451098435094ba", "testCaseId": "1cbb38d9e194ea6029099c92ca0fa145", "fullName": "tests.auth.test_user_login.TestUserLogin#test_login_user_wrong_field_error", "labels": [{"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "ZenBook"}, {"name": "thread", "value": "4860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_user_login"}]}