{"name": "Ошибка авторизации с неверным email или паролем", "status": "passed", "steps": [{"name": "Авторизация пользователя", "status": "passed", "parameters": [{"name": "user_data", "value": "{'email': 0, 'password': 'Wx71I7ynMhn', 'name': 'Waemowibuj'}"}, {"name": "token", "value": "'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmJlMGRmOWVkMjgwMDAxYjUzZDdkZCIsImlhdCI6MTczNTEyMzE2NywiZXhwIjoxNzM1MTI0MzY3fQ.DNwO3IH4Nwqhpz67s6mZvvMO13_r9u6t1azhJNbdVvw'"}], "start": 1735123167109, "stop": 1735123167263}], "parameters": [{"name": "field", "value": "'email'"}], "start": 1735123167109, "stop": 1735123167264, "uuid": "d727bc87-b64c-4c6b-a71f-7c916bec104a", "historyId": "999960981d19aef5d8bd4d9aa97b8440", "testCaseId": "1cbb38d9e194ea6029099c92ca0fa145", "fullName": "tests.auth.test_user_login.TestUserLogin#test_login_user_wrong_field_error", "labels": [{"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "ZenBook"}, {"name": "thread", "value": "4860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_user_login"}]}